version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests: [unique, not_null]
  - name: dim_accounts
    columns:
      - name: account_id
        tests: [unique, not_null]
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
  - name: fct_transactions
    columns:
      - name: transaction_id
        tests: [unique, not_null]
      - name: account_id
        tests:
          - relationships:
              to: ref('dim_accounts')
              field: account_id
